name: lint

on: [push]

jobs:
  ruff-format:
    name: Check code formatting with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM (Python 3.12)
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pdm sync -dG lint
      - name: Run Ruff formatter
        run: ruff format --diff

  ruff-check:
    name: Check code linting with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM (Python 3.12)
        uses: pdm-project/setup-pdm@v4
        with:
            python-version: "3.12"
      - name: Install dependencies
        run: |
          pdm sync -dG lint
      - name: Run Ruff formatter
        run: ruff check --output-format=github

  pyright:
    name: Run typechecking with pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM (Python 3.12)
        uses: pdm-project/setup-pdm@v4
        with:
            python-version: "3.12"
      - name: Install dependencies
        run: |
          pdm sync -dG lint
      - name: Run pyright
        run: pyright
